minecraftVersion: "1.20.1"
modLoader: "forge"
modList:
- slug: "biomes-o-plenty"
  versionNumber: "19.0.0.96"
  versionId: "jxUqRzSD"
- slug: "claim"
  versionNumber: "1.0.2"
  versionId: "v5T21hCF"
- slug: "creativecore"
  versionNumber: "2.12.32"
  versionId: "IbFWHI5h"
- slug: "delightful"
  versionNumber: "3.7.6-1.20.1"
  versionId: "VeYJRbNt"
- slug: "dynamictrees"
  versionNumber: "1.20.1-1.4.7"
  versionId: "XFTnlYsq"
- slug: "fallingtree"
  versionNumber: "1.20.1-4.3.4"
  versionId: "NrtzFkZE"
- slug: "farmers-delight"
  versionNumber: "1.20.1-1.2.9"
  versionId: "8rPF1pFi"
- slug: "furniture-beetle"
  versionNumber: "0.7.0"
  versionId: "yc0hcKjH"
- slug: "glitchcore"
  versionNumber: "0.0.1.1"
  versionId: "pYPZ5MNI"
- slug: "missing-wilds"
  versionNumber: "v1.2.1+1.20.1-forge"
  versionId: "CUyy6u4Y"
- slug: "moogs-voyager-structures"
  versionNumber: "5.0.21"
  versionId: "3jEMNi1E"
- slug: "natures-compass"
  versionNumber: "1.20.1-1.11.2-forge"
  versionId: "Og40jCNX"
- slug: "patchouli"
  versionNumber: "1.20.1-84.1-forge"
  versionId: "8Qyw08ld"
- slug: "psi"
  versionNumber: "1.20.1-1.20.1-102"
  versionId: "PVwCHaWy"
- slug: "simplecore-api"
  versionNumber: "1.20.1-6.0.1.2"
  versionId: "BgMT8cxQ"
- slug: "smartbrainlib"
  versionNumber: "1.15"
  versionId: "YkeJNm33"
- slug: "terrablender"
  versionNumber: "3.0.1.10"
  versionId: "zGconCHG"
- slug: "towns-and-towers"
  versionNumber: "1.12"
  versionId: "7ZwnSrVW"
- slug: "xaeros-world-map"
  versionNumber: "1.39.12_Forge_1.20"
  versionId: "ATTRzxT3"
- slug: "xaeros-minimap"
  versionNumber: "25.2.10_Forge_1.20"
  versionId: "VfhlV9am"
- slug: "ad-astra"
  versionNumber: "1.15.20"
  versionId: "Qf7QFXk2"
- slug: "aether"
  versionNumber: "1.20.1-1.5.2-neoforge"
  versionId: "2411kUqF"
- slug: "alcocraft"
  versionNumber: "2.1.0+1.20.1"
  versionId: "o7aK5zaB"
- slug: "alekiships"
  versionNumber: "1.0.14"
  versionId: "VX4fjmf1"
- slug: "architectury-api"
  versionNumber: "9.2.14+forge"
  versionId: "1MKTLiiG"
- slug: "odyssey-allies"
  versionNumber: "1.0.10"
  versionId: "r0eKAc5z"
- slug: "athena-ctm"
  versionNumber: "3.1.2"
  versionId: "DULOQFj7"
- slug: "bagus-lib"
  versionNumber: "1.20.1-5.6.1"
  versionId: "EutpppUn"
- slug: "better-combat"
  versionNumber: "1.8.6+1.20.1-forge"
  versionId: "UjlaL0Fm"
- slug: "blueprint"
  versionNumber: "7.1.3"
  versionId: "xtEwbO0X"
- slug: "botarium"
  versionNumber: "2.3.4"
  versionId: "O7D6FTfW"
- slug: "odyssey-claims"
  versionNumber: "1.0.8"
  versionId: "vtGe3auv"
- slug: "caelus"
  versionNumber: "3.2.0+1.20.1"
  versionId: "mRry0DgY"
- slug: "carry-on"
  versionNumber: "2.1.2.7"
  versionId: "edGQD16r"
- slug: "cc-tweaked"
  versionNumber: "1.116.2"
  versionId: "HOGBfJ9m"
- slug: "citadel"
  versionNumber: "2.6.2"
  versionId: "oD1qDb1C"
- slug: "cloth-config"
  versionNumber: "11.1.136+forge"
  versionId: "t8TXrZvZ"
- slug: "coroutil"
  versionNumber: "1.20.1-1.3.7"
  versionId: "6rPDKAT8"
- slug: "cosmetic-armor"
  versionNumber: null
  versionId: null
- slug: "create"
  versionNumber: "mc1.20.1-6.0.8"
  versionId: "8amzvn9x"
- slug: "create-connected"
  versionNumber: "1.1.10-mc1.20.1"
  versionId: "saiZ8AwJ"
- slug: "create-misc-and-things"
  versionNumber: "4.0"
  versionId: "c7ob4jVD"
- slug: "create-power-loader"
  versionNumber: "2.0.3-mc1.20.1"
  versionId: "gQuz8jcV"
- slug: "create-ultimate-factory"
  versionNumber: "2.2.1"
  versionId: "feuPrlUZ"
- slug: "create-wizardry"
  versionNumber: "0.2.3"
  versionId: "BUK0p8gn"
- slug: "createaddition"
  versionNumber: "forge-1.20.1-1.3."
  versionId: "9LgyB6Yb"
- slug: "create-big-cannons"
  versionNumber: "5.9.1"
  versionId: "hdPNh3oa"
- slug: "cristel-lib"
  versionNumber: "1.1.6-forge"
  versionId: "DOsSK4NK"
- slug: "cumulus"
  versionNumber: "1.20.1-1.0.0-neoforge"
  versionId: "crhMXBde"
- slug: "curios"
  versionNumber: "5.14.1+1.20.1"
  versionId: "IPQlZkz1"
- slug: "lambdynamiclights"
  versionNumber: null
  versionId: null
- slug: "earthmobs"
  versionNumber: "1.20.1-10.5.0"
  versionId: "l8g8eoEi"
- slug: "ecologics"
  versionNumber: "2.2.2"
  versionId: "cUQnkGgj"
- slug: "embeddium"
  versionNumber: "0.3.31+mc1.20.1"
  versionId: "UTbfe5d1"
- slug: "epic-knights-shields-armor-and-weapons"
  versionNumber: "9.31"
  versionId: "wnmBK9Yd"
- slug: "fantasy-furniture"
  versionNumber: "9.0.0"
  versionId: "o3iXCBa8"
- slug: "ferrite-core"
  versionNumber: "6.0.1"
  versionId: "DG5Fn9Sz"
- slug: "geckolib"
  versionNumber: "4.8.2"
  versionId: "aVW7Z5da"
- slug: "gravestone-mod"
  versionNumber: "forge-1.20.1-1.0.35"
  versionId: "q9kZE5Xo"
- slug: "guard-villagers"
  versionNumber: "1.20.1-1.6.11"
  versionId: "88t2ts1p"
- slug: "incubation"
  versionNumber: "4.0.4"
  versionId: "WAqOPLlv"
- slug: "inventory-sorter-configurable"
  versionNumber: "23.1.9"
  versionId: "ItiqYtL3"
- slug: "iron-chests"
  versionNumber: "1.20.1-14.4.4"
  versionId: "YjbOtYwN"
- slug: "irons-spells-n-spellbooks"
  versionNumber: "1.20.1-3.4.0.9"
  versionId: "9dM8iFPD"
- slug: "jei"
  versionNumber: "15.20.0.125"
  versionId: "fng9dc76"
- slug: "legendary-monsters"
  versionNumber: "1.20.1"
  versionId: "LtJURbgf"
- slug: "markdownmanual"
  versionNumber: "MC1.20.1-forge-1.2.5"
  versionId: "oyfNmTsm"
- slug: "macaws-furniture"
  versionNumber: "3.4.1"
  versionId: "mvGf4LNK"
- slug: "minecraft-comes-alive-reborn"
  versionNumber: "7.6.12+1.20.1"
  versionId: "oKQb47oF"
- slug: "moogs-structure-lib"
  versionNumber: "1.1.0-1.20-1.20.4"
  versionId: "xtqWb6du"
- slug: "mowzies-mobs"
  versionNumber: "1.7.3"
  versionId: "WMCZ4t5U"
- slug: "naturalist"
  versionNumber: "5.0pre3-forge"
  versionId: "Cx95h37p"
- slug: "oc2r"
  versionNumber: "2.2.6"
  versionId: "mVwyKgu3"
- slug: "oculus"
  versionNumber: "1.20.1-1.8.0"
  versionId: "iQ1SwGc3"
- slug: "packet-fixer"
  versionNumber: "3.3.1"
  versionId: "96y8nmkX"
- slug: "pams-harvestcraft-2-crops"
  versionNumber: null
  versionId: null
- slug: "pams-harvestcraft-2-food-core"
  versionNumber: "1.0.5"
  versionId: "RLPfpN1a"
- slug: "pams-harvestcraft-2-food-extended"
  versionNumber: "1.0.0"
  versionId: "ZHPzQtqH"
- slug: "pams-harvestcraft-2-trees"
  versionNumber: null
  versionId: null
- slug: "plasmo-voice"
  versionNumber: "forge-1.20.1-2.1.6"
  versionId: "jUfq4vP0"
- slug: "playeranimator"
  versionNumber: "1.0.2-rc1+1.20-forge"
  versionId: "xe2EVE6q"
- slug: "radium"
  versionNumber: "0.12.4"
  versionId: "n947JjJH"
- slug: "resourceful-config"
  versionNumber: "2.1.3"
  versionId: "DERs8u7v"
- slug: "resourceful-lib"
  versionNumber: "2.1.29"
  versionId: "OhsHaCcW"
- slug: "rpl"
  versionNumber: "2.1.0"
  versionId: "MxClZxbS"
- slug: "spark"
  versionNumber: "1.10.53-forge"
  versionId: "4FXHDE9F"
- slug: "stateobserver"
  versionNumber: "1.4.3"
  versionId: "BHMS4baI"
- slug: "modern-warfare-cubed"
  versionNumber: null
  versionId: null
- slug: "create-tfmg"
  versionNumber: "1.0.2c"
  versionId: "ZdvRpjTA"
- slug: "torohealth-damage-indicators-updated"
  versionNumber: "1.20.1-forge-1"
  versionId: "ovWvJ3oj"
- slug: "the-twilight-forest-unofficial"
  versionNumber: null
  versionId: null
- slug: "u-team-core"
  versionNumber: "5.1.4.382"
  versionId: "Xdq16yXj"
- slug: "useful-backpacks"
  versionNumber: "2.0.1.124"
  versionId: "XhB0FxvI"
- slug: "worldedit"
  versionNumber: null
  versionId: null
- slug: "zombie-awareness"
  versionNumber: "1.20.1-1.13.1"
  versionId: "vmo9rLxO"