minecraftVersion: "1.20.1"
modLoader: "forge"
modList:
  "create": "mc1.20.1-6.0.8"
  "create_factory_logistics": "1.4.7"
  "create-enchantment-industry": "1.3.3"
  "create-mobile-packages": "1.20.1-0.6.0-Beta-02"
  "create-radars": "0.3"
  "create-big-cannons": "5.9.1"