minecraftVersion: "1.20.1"
modLoader: "forge"
modList:
  "biomes-o-plenty": "19.0.0.96"
  "claim": "1.0.17"
  "creativecore": "2.12.32"
  "delightful": "3.7.6"
  "dynamictrees": "1.4.5"
  "fallingtree": "4.3.4"
  "farmers-delight": "1.2.9"
  "furniture-beetle": "0.7.0"
  "glitchcore": "0.0.1.1"
  "missing-wilds": "1.2.1"
  "moogs-voyager-structures": "5.0.21"
  "natures-compass": "1.11.2"
  "patchouli": "84.1"
  "psi": "102"
  "simplecore-api": "6.0.1.2"
  "smartbrainlib": "1.15"
  "terrablender": "3.0.1.10"
  "towns-and-towers": "1.12"
  "xaeros-world-map": "1.39.12"
  "xaeros-minimap": "25.2.10"
  "ad-astra": "1.15.20"
  "aether": "1.5.2"
  "alcocraft": "2.1.0"
  "alekiships": "1.0.14"
  "architectury-api": "9.2.14"
  "odyssey-allies": "1.0.10"
  "athena-ctm": "3.1.2"
  "bagus-lib": "5.6.1"
  "better-combat": "1.8.6"
  "blueprint": "7.1.3"
  "botarium": "2.3.4"
  "odyssey-claims": "1.0.8"
  "caelus": "3.2.0"
  "carry-on": "2.1.2.7"
  "cc-tweaked": "1.116.1"
  "citadel": "2.6.2"
  "cloth-config": "11.1.136"
  "coroutil": "1.3.7"
  "cosmetic-armor": "v1a"
  "create": "1.20.1-6.0.6"
  "create-connected": "1.1.7"
  "create-misc-and-things": "4.0A"
  "create-power-loader": "2.0.3"
  "create-ultimate-factory": "2.2.1"
  "create-wizardry": "0.2.3"
  "createaddition": "1.3.2"
  "create-big-cannons": "5.9.1"
  "cristel-lib": "1.1.6"
  "cumulus": "1.0.1"
  "curios": "5.14.1"
  "lambdynamiclights": "1.20.1.2"
  "earthmobs": "10.5.0"
  "ecologics": "2.2.2"
  "embeddium": "0.3.31"
  "epic-knights-shields-armor-and-weapons": "9.31"
  "fantasy-furniture": "9.0.0"
  "ferrite-core": "6.0.1"
  "geckolib": "4.8.2"
  "gravestone-mod": "1.0.35"
  "guard-villagers": "1.6.11"
  "incubation": "4.0.4"
  "inventory-sorter-configurable": "23.1.9"
  "iron-chests": "14.4.4"
  "irons-spells-n-spellbooks": "3.4.0.9"
  "jei": "15.20.0.116"
  "legendary-monsters": "1.9.8"
  "markdownmanual": "1.2.5"
  "macaws-furniture": "3.3.0"
  "minecraft-comes-alive-reborn": "7.6.12"
  "moogs-structure-lib": "1.0.1"
  "mowzies-mobs": "1.7.3"
  "naturalist": "4.0.3"
  "oc2r": "2.2.6"
  "oculus": "1.8.0"
  "packet-fixer": "3.3.0"
  "pams-harvestcraft-2-crops": "1.0.3"
  "pams-harvestcraft-2-food-core": "1.0.3"
  "pams-harvestcraft-2-food-extended": "1.0.0"
  "pams-harvestcraft-2-trees": "1.0.2"
  "plasmo-voice": "2.1.6"
  "playeranimator": "1.0.2-rc1"
  "radium": "0.12.4"
  "resourceful-config": "2.1.3"
  "resourceful-lib": "2.1.29"
  "rpl": "2.0.0"
  "spark": "1.10.53"
  "stateobserver": "1.4.3"
  "modern-warfare-cubed": "1.1.6-hotfix"
  "create-tfmg": "1.0.2c"
  "torohealth-damage-indicators-updated": "1.0.0"
  "the-twilight-forest-unofficial": "4.3.2508"
  "u-team-core": "5.1.4.382"
  "useful-backpacks": "2.0.1.124"
  "worldedit": "7.2.15"
  "zombie-awareness": "1.13.1"
